remote_theme: advaith1/time-machine
title:       Eggmotes Rich Presence
# The name of the repository
repotitle:   Eggmotes Rich Presence
# Description
description: Discord Rich Presence for the Eggmotes server
# Author
author:      advaith#9121
# Author URL
authorurl:   http://github.com/advaith1
# URL to the page. Usually https://orgname.github.io (put whatever's in the CNAME otherwise)
url:         https://rp.eggmotes.tk
